CREATE TABLE staging_flights (
    fl_date DATE,
    carrier VARCHAR(5),
    tail_num VARCHAR(10),
    flight_num INT,
    origin VARCHAR(5),
    origin_city VARCHAR(100),
    dest VARCHAR(5),
    dest_city VARCHAR(100),
    crs_dep_time INT,
    dep_time INT,
    dep_delay DECIMAL(6,2),
    crs_arr_time INT,
    arr_time INT,
    arr_delay DECIMAL(6,2),
    cancelled BOOLEAN,
    diverted BOOLEAN,
    carrier_delay DECIMAL(6,2),
    weather_delay DECIMAL(6,2),
    nas_delay DECIMAL(6,2),
    security_delay DECIMAL(6,2),
    late_aircraft_delay DECIMAL(6,2),
    missing_tail_num BOOLEAN
);